
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 28 04:02:15 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 25;
  public static final int MULT = 17;
  public static final int CHAR = 43;
  public static final int P = 36;
  public static final int CAR = 15;
  public static final int PC = 29;
  public static final int INT = 40;
  public static final int PA = 28;
  public static final int OBJECTS = 2;
  public static final int C = 35;
  public static final int NOT = 16;
  public static final int MENORIGUAL = 22;
  public static final int AND = 26;
  public static final int IGUAL = 24;
  public static final int OR = 27;
  public static final int BOOL = 42;
  public static final int DIV = 18;
  public static final int CC = 31;
  public static final int CA = 30;
  public static final int PROCESS = 3;
  public static final int ID = 10;
  public static final int MAYORIGUAL = 23;
  public static final int EOF = 0;
  public static final int LC = 32;
  public static final int TRUE = 13;
  public static final int error = 1;
  public static final int BUCLE = 6;
  public static final int EXCC = 34;
  public static final int MENOS = 9;
  public static final int MENOR = 20;
  public static final int MOD = 19;
  public static final int VOID = 39;
  public static final int REAL = 12;
  public static final int MAYOR = 21;
  public static final int ENT = 11;
  public static final int ENUM = 4;
  public static final int FLOAT = 41;
  public static final int INTC = 33;
  public static final int ASIGN = 7;
  public static final int FALSE = 14;
  public static final int STRUCT = 5;
  public static final int DP = 37;
  public static final int PRINT = 38;
  public static final int MAS = 8;
}

